name: Test Dev Environment Setup Script

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Manually trigger the workflow via GitHub UI

jobs:
  test-script:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # Checkout the repository code

    # Check if this is a merge commit
    - name: Check if merge commit
      id: check_merge
      run: |
        # Check if the current commit is a merge commit
        if [ $(git log --pretty=%P -n 1 HEAD | wc -w) -gt 1 ]; then
          echo "This is a merge commit."
        else
          echo "This is not a merge commit. Exiting."
          exit 0  # Exit early if not a merge commit
        fi

    # Check for changes to relevant files (e.g., PowerShell scripts)
    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code --quiet HEAD^ HEAD -- SetupDevEnv.ps1 || echo "Changes detected"

    # Exit if no changes were detected
    - name: Exit if no changes
      if: steps.check_changes.outputs.diff == 'Changes detected'
      run: |
        echo "No changes detected, skipping workflow."
        exit 0  # Exit early if no changes

    - name: Set up Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force;
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Run PowerShell Script
      run: |
        powershell -ExecutionPolicy Bypass -File ./SetupDevEnv.ps1

    - name: Verify Installation
      run: |
        choco list --local-only
        git --version
        node --version
        python --version
